[package]
name = "ImgSync"
version = "0.1.0"
authors = ["Isato Matsushita <22887835+bean1310@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
